workflows:
  android-build:
    name: Kintara APK Build

    max_build_duration: 60

    environment:
      android_sdk: "35"

    scripts:
      - name: Build Kintara APK
        script: |
          cd kintara_src
          chmod +x build.sh
          ./build.sh

    artifacts:
      - kintara_src/out/*.apk
