workflows:
  android-build:
    name: Kintara APK Build

    max_build_duration: 60

    scripts:
      - name: Build APK
        script: |
          cd KintaraMarket-v2.2.0-kintara-play-source-modified/kintara_src
          chmod +x gradlew
          ./gradlew assembleDebug

    artifacts:
      - KintaraMarket-v2.2.0-kintara-play-source-modified/kintara_src/app/build/outputs/**/*.apk
