from __future__ import annotations

"""English-only text catalog for the administrator interface.

The customer-facing interface remains localized. Administrator screens use this
catalog so their language is predictable and independent of the admin account's
selected customer language.
"""

ADMIN_TEXT: dict[str, str] = {
    "admin.molten.channel_invalid": "The channel ID must be a negative integer.",
    "admin.molten.channel_prompt": "Send the private channel numeric ID, for example: <code>-1004463401405</code>",
    "admin.molten.channel_saved": "Channel ID saved.",
    "admin.molten.publish_failed": "Accurate data is not ready yet, or the channel is not configured correctly.",
    "admin.molten.publish_now": "Publish to Channel",
    "admin.molten.publish_success": "The latest report was published to the channel.",
    "admin.molten.set_channel": "Set Channel",
    "admin.molten.use_env_cookie": "Use .env Cookie",
    "admin.plan.access_mode": "Access mode",
    "admin.plan.free": "Free",
    "admin.plan.make_free": "Switch to Free Access",
    "admin.plan.make_paid": "Switch to Paid Access",
    "admin.plan.mode_free": "This service is now available without payment.",
    "admin.plan.mode_paid": "Payment is now required for this service.",
    "admin.plan.paid": "Paid",
    "admin.plan.revoked_free": "\nPrevious free access was revoked for {count} user(s).",
    "custom.admin.ember.autostart_prompt": "Auto-start is enabled. Send the central Kintara Cookie; after validation, the Come To Molten CMD will start automatically.",
    "custom.admin.ember.cookie_saved": "✅ The central Cookie was encrypted and saved. {detail}",
    "custom.admin.ember.enabled_prompt": "Come To Molten was enabled and its workspace was created:\n<code>{workspace}</code>\n\nSend the central Kintara Cookie. After encryption, the Come To Molten CMD will start automatically.",
    "custom.admin.ember.start_prompt": "Come To Molten workspace created:\n<code>{workspace}</code>\n\nSend the central Kintara Cookie. The message will be deleted, the value will be encrypted, and the Come To Molten CMD will start automatically.",
    "custom.admin.ember.workspace_line": "\nWorkspace: <code>{workspace}</code>",
    "custom.admin.payment.manual_button": "Require Final Admin Approval for Kintara",
    "custom.admin.payment.manual_disabled": "⚠️ Final admin approval is disabled. New verified payments may activate automatically.",
    "custom.admin.payment.manual_enabled": "✅ Kintara payments now require final admin approval before activation.",
    "custom.payment.admin.approved": "Order approved.",

    "telegram.admin_keyboards.033aae396210": "⬅️ Features",
    "telegram.admin_keyboards.068b37d2ba88": "⛔ Disable",
    "telegram.admin_keyboards.0b6734303599": "⬅️ Payments",
    "telegram.admin_keyboards.0dc9058de19c": "⬅️ Games",
    "telegram.admin_keyboards.1473364c6d2a": "⏹ Stop All Workers",
    "telegram.admin_keyboards.17ad6ffb0047": "🌐 Change RPC URL",
    "telegram.admin_keyboards.18459dcb8c8c": "✅ Enable Plan",
    "telegram.admin_keyboards.1e043a373f5a": "🔢 Change Total Capacity",
    "telegram.admin_keyboards.1f6b6a5442f1": "👁 Show",
    "telegram.admin_keyboards.2308150185d2": "✅ Disable Maintenance",
    "telegram.admin_keyboards.23b1ac1df584": "🧹 Remove Database Override",
    "telegram.admin_keyboards.23f523ce7ff5": "⛔ Disable Service",
    "telegram.admin_keyboards.2a54bac718c4": "▶️ Enable Auto-start",
    "telegram.admin_keyboards.2a6f2885fa96": "👥 Trial Claims",
    "telegram.admin_keyboards.2be4012b9c60": "❤️ Heartbeat Timeout",
    "telegram.admin_keyboards.2c3b5c2ede63": "⏹ Stop Game Workers",
    "telegram.admin_keyboards.31aa8a62bdd3": "🚧 Maintenance",
    "telegram.admin_keyboards.37791bc1336e": "❌ Reject",
    "telegram.admin_keyboards.3b870c31b9ad": "⚙️ System Settings",
    "telegram.admin_keyboards.3e3ca8cd3d0f": "✅ Enable Service",
    "telegram.admin_keyboards.3fba98ac5877": "🔗 Change Support URL",
    "telegram.admin_keyboards.4217b25ba5fb": "👥 Users with Access",
    "telegram.admin_keyboards.45083d2eab1b": "♻️ Restart Game Workers",
    "telegram.admin_keyboards.46523cfcb565": "🙈 Hide from Users",
    "telegram.admin_keyboards.4abbfd9e6b65": "⏱ Change Update Interval",
    "telegram.admin_keyboards.4ad8283620a5": "🧹 Restore Default",
    "telegram.admin_keyboards.4ddf3686ebce": "⬅️ Select Game",
    "telegram.admin_keyboards.56d5abcea243": "🎮 Games",
    "telegram.admin_keyboards.56f92d8d7c34": "🔄 Reload Settings",
    "telegram.admin_keyboards.58b9fb95218e": "💳 Payments and Wallets",
    "telegram.admin_keyboards.5bcb8dcdb14c": "🇬🇧 Change English Message",
    "telegram.admin_keyboards.602380d26723": "🧩 Game Features",
    "telegram.admin_keyboards.640430c090df": "🧩 Features",
    "telegram.admin_keyboards.6d736b7d97e0": "✅ Enable Trial",
    "telegram.admin_keyboards.6dc380856853": "🏦 Change Wallet Address",
    "telegram.admin_keyboards.7333e96e83b1": "👁 Show in Bot",
    "telegram.admin_keyboards.7bf99e7b9326": "⛔ Disable Trial",
    "telegram.admin_keyboards.7d9e8eb75f02": "🔐 Set Central Cookie",
    "telegram.admin_keyboards.814ea8f2bd4e": "✅ Network Confirmations",
    "telegram.admin_keyboards.8e245a063309": "⬅️ Admin Panel",
    "telegram.admin_keyboards.8fc079fba603": "🚧 Enable Maintenance",
    "telegram.admin_keyboards.8fd6826dbfea": "🎁 Free Trial",
    "telegram.admin_keyboards.96ab62ac6224": "✅ Enable",
    "telegram.admin_keyboards.9756cad82563": "⬅️ Game Plans",
    "telegram.admin_keyboards.9b689874b9a2": "📅 Change Duration (Days)",
    "telegram.admin_keyboards.9cd2691b47dc": "⏱ Payment Check Interval",
    "telegram.admin_keyboards.9f05b40f1156": "🧾 Orders",
    "telegram.admin_keyboards.9fccc86a90e9": "🛠 Workers",
    "telegram.admin_keyboards.a1c18aafd3c5": "♻️ Restart Active Subscriptions",
    "telegram.admin_keyboards.a86a3fb0d4d0": "🎁 Game Trial",
    "telegram.admin_keyboards.aa95ee3d6d7f": "👁 Show to Users",
    "telegram.admin_keyboards.b0b633a345de": "🪙 Change Mint/Contract",
    "telegram.admin_keyboards.b4acd75cfc83": "🔒 Controlled by Central Server",
    "telegram.admin_keyboards.b63e8c195808": "💎 Plans",
    "telegram.admin_keyboards.b868ffdcfd56": "🗃 Backup Retention Count",
    "telegram.admin_keyboards.b8aa8e9f05b1": "🔥 Come To Molten",
    "telegram.admin_keyboards.bc84fdc5b472": "💾 Automatic Backup Interval",
    "telegram.admin_keyboards.bcda39409f06": "⏸ Disable Auto-start",
    "telegram.admin_keyboards.be6915f659ed": "⬅️ Game Trials",
    "telegram.admin_keyboards.c63a97fe5bf4": "👥 Users",
    "telegram.admin_keyboards.cc6f020d058e": "💎 Game Plans",
    "telegram.admin_keyboards.cf21f2b049f3": "💾 Create Backup",
    "telegram.admin_keyboards.cf95e35d5aab": "💵 Change USDC Price",
    "telegram.admin_keyboards.d00c303800ed": "♻️ Worker Restart Limit",
    "telegram.admin_keyboards.d15a22e98a77": "⏳ Subscription Expiry Warning",
    "telegram.admin_keyboards.d3bcdcb0b8f9": "🇮🇷 Change Persian Message",
    "telegram.admin_keyboards.d9b8cf0cd3c1": "▶️ Start CMD",
    "telegram.admin_keyboards.dd3ae9d8f210": "⛔ Disable Plan",
    "telegram.admin_keyboards.f830b3f8e741": "👤 Change Support Handle",
    "telegram.admin_keyboards.f9638d8b79aa": "⏹ Stop CMD",
    "telegram.admin_keyboards.f9e29f9e30aa": "🆘 Support",
    "telegram.admin_keyboards.fccc1d71825a": "🙈 Hide",
    "telegram.admin_keyboards.fdbd3f56162f": "⏱ Change Trial Duration",

    "telegram.routers.admin.04fae85c26d1": "✅ Payment network ",
    "telegram.routers.admin.099bf20633c3": "Merchant is managed only by the central server.",
    "telegram.routers.admin.0a1fb798b8eb": "This feature is controlled by the central server.",
    "telegram.routers.admin.0afbd7295df0": "</b>\nDuration: <b>",
    "telegram.routers.admin.0d53ad78620f": "</b>\n\nStatus: <b>",
    "telegram.routers.admin.111b5339be36": "🎁 Select a game to manage its free trial:",
    "telegram.routers.admin.155460a6fd73": "",
    "telegram.routers.admin.19fbc1699397": "</b>\nActive workers: <b>",
    "telegram.routers.admin.1a84bfa88670": "✅ Subscription extended until <code>",
    "telegram.routers.admin.1c8d94b0eabf": "Format: <code>/restartaccount ACCOUNT_ID</code>",
    "telegram.routers.admin.1cdd3844c5d3": " seconds</b>\nExpiry warning: <b>",
    "telegram.routers.admin.1da2ed76cd34": "</b>\n\nEnabled: <b>",
    "telegram.routers.admin.1eef86e516ba": "This section is available to administrators only.",
    "telegram.routers.admin.1fc836964f3b": "✅ Feature updated.",
    "telegram.routers.admin.2058e209a592": "No trial has been used yet.",
    "telegram.routers.admin.20922a4d9875": "✅ Maintenance message saved.",
    "telegram.routers.admin.21b938b85906": "Invalid capacity.",
    "telegram.routers.admin.21fea35fbb5d": "✅ Account plan changed to <b>",
    "telegram.routers.admin.2202351aa22c": "✅ System setting saved.",
    "telegram.routers.admin.28e55aef2265": "</b>\nSubscriptions: <b>",
    "telegram.routers.admin.2a31ccb79e67": "✅ Plan ",
    "telegram.routers.admin.2a9c6031c7f6": "</b>\nAuto-start: <b>",
    "telegram.routers.admin.2cb9d0bf92b6": "; central server error: ",
    "telegram.routers.admin.330614083250": "Send the new USDC price, for example: <code>4.99</code>.",
    "telegram.routers.admin.33579e962656": "Select a feature. Central-server settings, when available, have final priority.",
    "telegram.routers.admin.340f51470859": "</b>\nRestart limit: <b>",
    "telegram.routers.admin.35809ac24438": "</b> worker(s) stopped.",
    "telegram.routers.admin.35eb7b5fed55": "</code>\n\n<b>Top servers</b>\n",
    "telegram.routers.admin.3701bef2c49f": "</b> changed.",
    "telegram.routers.admin.396f6497b4dd": "✅ Network setting saved. It applies to new orders.",
    "telegram.routers.admin.39e7769e289b": "👥 <b>Recent Trial Claims</b>\n",
    "telegram.routers.admin.3a1d4d0b4ea6": "🚧 <b>Maintenance</b>\n\nStatus: <b>",
    "telegram.routers.admin.3b29075e050a": "🧩 Select a game to manage features:",
    "telegram.routers.admin.3be0419687e6": "An approved order cannot be rejected.",
    "telegram.routers.admin.3e1b6f3e34ee": "🎮 <b>Game Management</b>\n🟢/🔴 runtime status — 👁/🙈 bot visibility",
    "telegram.routers.admin.3e6bcc734f3c": "No transaction hash has been submitted for this order.",
    "telegram.routers.admin.403ad06d7c0a": "⏹ Stopped <b>",
    "telegram.routers.admin.41abae56572a": "Send the number of backup files to keep; minimum 1.",
    "telegram.routers.admin.4226d96303ba": "Send the update interval in seconds; recommended: <code>20</code>.",
    "telegram.routers.admin.429ea30401a7": "🎁 <b>Free Trial — ",
    "telegram.routers.admin.4770f8ae422a": "</b>\nAccounts: <b>",
    "telegram.routers.admin.4a97e116e5c7": "How many hours before expiry should the user be notified?",
    "telegram.routers.admin.4cb78b996a4b": "Invalid message length.",
    "telegram.routers.admin.4cd5331c9247": "</code>\nEnabled: <b>",
    "telegram.routers.admin.4d20912f1585": "</b>\nLast update: <code>",
    "telegram.routers.admin.4f6d6282fd21": "❌ Backup error: <code>",
    "telegram.routers.admin.50cbbb80324d": "💾 Backup created.",
    "telegram.routers.admin.528b10fcc311": "No users found.",
    "telegram.routers.admin.53d0644851f1": "",
    "telegram.routers.admin.54bca6c45468": "The central Cookie is invalid.",
    "telegram.routers.admin.559c727c2565": "Select a plan:",
    "telegram.routers.admin.56135df8fbe4": "</b>\nPersian message: ",
    "telegram.routers.admin.583185e23fe8": "Send the total trial capacity; use <code>0</code> for unlimited.",
    "telegram.routers.admin.58af843d33eb": "</b>.\n\n⚠️ Never send a private key, recovery phrase, or seed phrase. Send <code>/cancel</code> to cancel.",
    "telegram.routers.admin.58c54168f817": "Unlimited",
    "telegram.routers.admin.5f639b680c2b": "✅ Database overrides removed; `.env` values are active again.",
    "telegram.routers.admin.602fca45b277": "Administrator access is required.",
    "telegram.routers.admin.61ce8f959ab3": "New value for <b>",
    "telegram.routers.admin.621cc67ba714": "Send the heartbeat timeout in seconds; minimum 30.",
    "telegram.routers.admin.62ac6685ebf7": "The order has already been approved.",
    "telegram.routers.admin.6603c735de4c": "👥 <b>Recent Users</b>",
    "telegram.routers.admin.68ae9548c296": "⚙️ <b>System Settings</b>\n\nPayment checks: <b>",
    "telegram.routers.admin.68f77dc9b35e": "Invalid price.",
    "telegram.routers.admin.695efa26111a": "</code>\nGame enabled: <b>",
    "telegram.routers.admin.6aa416ea8610": "Send the payment check interval in seconds; minimum 15.",
    "telegram.routers.admin.6b7c13bccfe4": "</b>\nCrypto orders: <b>",
    "telegram.routers.admin.6f637966671d": "Enabled",
    "telegram.routers.admin.6f83c51f779a": "Duration must be between 1 and 3650 days.",
    "telegram.routers.admin.7173c2e29ede": "</b>\nActive workers: <b>",
    "telegram.routers.admin.7251dbec5941": " seconds</b>\nBackups retained: <b>",
    "telegram.routers.admin.7386d0fe35a5": "💾 Secure backup created.",
    "telegram.routers.admin.75fd0511b2e9": ". Workers stopped: ",
    "telegram.routers.admin.7672a423a606": "Creating backup...",
    "telegram.routers.admin.799c08248ff3": "No registered users.",
    "telegram.routers.admin.7cfb7c75e9fb": "🛡 <b>Platform Admin Panel</b>\n\nUsers: <b>",
    "telegram.routers.admin.7d1893295245": "</b> — failed: <b>",
    "telegram.routers.admin.7e0b08f62a55": "Format: <code>/runaccount ACCOUNT_ID</code>",
    "telegram.routers.admin.7e2f1eaa62bc": " USDC</b>\nDuration: <b>",
    "telegram.routers.admin.817f2eae7343": "\n\n🔒 This feature can only be changed by the central server.",
    "telegram.routers.admin.81f17c729d72": "✅ Database and local settings reloaded.",
    "telegram.routers.admin.845e06056b52": "A Base address must start with 0x and contain 40 hexadecimal characters.",
    "telegram.routers.admin.8531f9b0b849": "</b>\nGame accounts: <b>",
    "telegram.routers.admin.86b43fbbff07": "🆘 <b>Support</b>\n\nHandle: <code>",
    "telegram.routers.admin.873bc9171517": "Invalid admin operation.",
    "telegram.routers.admin.8886158fbbd7": "</b>\n\nAll changes in this panel are stored in the database.",
    "telegram.routers.admin.8a71a0811d94": "Merchant can only be enabled by the central server.",
    "telegram.routers.admin.8af6c766a463": "🔥 <b>Come To Molten</b>\n\nCentral CMD: <b>",
    "telegram.routers.admin.8c1d5408696d": " minutes</b>\nTotal capacity: <b>",
    "telegram.routers.admin.8c66df35b1d7": "Payment approved and service activated.",
    "telegram.routers.admin.8fa19d6d90dc": "</b>\nUsed trials: <b>",
    "telegram.routers.admin.906355b636ab": "🧾 <b>Pending Orders</b>",
    "telegram.routers.admin.9181590e0672": "Operation cancelled.",
    "telegram.routers.admin.93799ccbd656": "Send the central Kintara Cookie. The message will be deleted immediately and the value will be encrypted.\nThis account is used only to retrieve server information.",
    "telegram.routers.admin.974a180607d1": "✅ Support setting saved.",
    "telegram.routers.admin.981311490c22": "✅ Plan setting saved.",
    "telegram.routers.admin.99d70345c814": "</b>\nCentral Cookie: <b>",
    "telegram.routers.admin.9aa0208d2eab": "✅ Free trial ",
    "telegram.routers.admin.9d27a6ae1977": "Invalid value. Never send a private key or recovery phrase.",
    "telegram.routers.admin.9db9378e6ebd": "</b>\nCome To Molten users: <b>",
    "telegram.routers.admin.9ecc687d819e": "Not configured",
    "telegram.routers.admin.9fa15a68a2e3": "✅ Maintenance ",
    "telegram.routers.admin.a00806d40606": "✅ Game runtime ",
    "telegram.routers.admin.a073b87c2875": "Order not found.",
    "telegram.routers.admin.a10f2132fbb3": " loaded.",
    "telegram.routers.admin.a464e38c86be": "Configure the wallet and Mint/Contract first.",
    "telegram.routers.admin.a5ac1b4f54dd": "</code>.",
    "telegram.routers.admin.a728d962e233": " days</b>",
    "telegram.routers.admin.a7b8355e452b": "No",
    "telegram.routers.admin.a9b2808c7d48": "Duration must be between 1 and 43200 minutes.",
    "telegram.routers.admin.ac80c4fc51ae": "The number must be between ",
    "telegram.routers.admin.ae370194313a": " seconds</b>\nNetwork confirmations: <b>",
    "telegram.routers.admin.af16e31ef2fe": "The link must start with https://.",
    "telegram.routers.admin.afcb410b5cc2": "Yes",
    "telegram.routers.admin.afccbce6bc38": "</b>\nMaintenance: <b>",
    "telegram.routers.admin.b00a83f1cf3b": "</b>\n\nID: <code>",
    "telegram.routers.admin.b0d9b1cba153": "Running",
    "telegram.routers.admin.b0de584316de": " user(s)",
    "telegram.routers.admin.b15872b61e56": "Send the plan duration in days, for example: <code>7</code>.",
    "telegram.routers.admin.b166f39076c7": "✅ No pending orders.",
    "telegram.routers.admin.b1d67399cf5c": "The order plan is disabled or no longer available.",
    "telegram.routers.admin.b74df5e64dff": "The handle must look like @SupportBot.",
    "telegram.routers.admin.b82211b0fd8d": "</b>\nVisible in bot: <b>",
    "telegram.routers.admin.bafc44588818": "Stopped",
    "telegram.routers.admin.c0461f7159b3": "RPC must start with http:// or https://.",
    "telegram.routers.admin.c04b94250e86": "</b>\nUsed: <b>",
    "telegram.routers.admin.c0daaabc2042": "Format: <code>/reject ORD-...</code>",
    "telegram.routers.admin.c2920de650a8": "Official USDC Mint/Contract",
    "telegram.routers.admin.c4727b0e6a25": "🛠 <b>Workers</b>\n\nIn memory: <b>",
    "telegram.routers.admin.c6a8d9ad493a": "Send the full support URL starting with <code>https://</code>.",
    "telegram.routers.admin.c82949cc3022": "Format: <code>/approve ORD-...</code>",
    "telegram.routers.admin.c881fd608e29": "✅ Game visibility ",
    "telegram.routers.admin.c89940bd0f4c": "Invalid Solana address.",
    "telegram.routers.admin.c976d8221569": "Format: <code>/stopaccount ACCOUNT_ID</code>",
    "telegram.routers.admin.c99b9757a84e": "💳 <b>Payments and Wallets</b>\n\nOnly public wallet addresses, Mint/Contract values, and RPC URLs are stored. Never send a private key or seed phrase.",
    "telegram.routers.admin.ca70527ecd90": "✅ Local override removed; default or central-server value is active.",
    "telegram.routers.admin.cb47ef23635f": "</b>\nPending orders: <b>",
    "telegram.routers.admin.cc57bcc77391": " and ",
    "telegram.routers.admin.cd99bfd023c6": "Hidden",
    "telegram.routers.admin.cea3e6ffebe4": "Send the new handle, for example: <code>@Support</code>.",
    "telegram.routers.admin.cfc5ad48801d": "✅ Update interval saved.",
    "telegram.routers.admin.d13b5ee971cb": "Send the new maintenance message.",
    "telegram.routers.admin.d2938ecf81cf": "♻️ Successful: <b>",
    "telegram.routers.admin.d367b207e8cd": "✅ Free-trial setting saved.",
    "telegram.routers.admin.d3d8e7a1dd5b": "Order rejected.",
    "telegram.routers.admin.d63067fdcb1e": "Format: <code>/changeplan ACCOUNT_ID PLAN</code>",
    "telegram.routers.admin.d9ba41681180": "Disabled",
    "telegram.routers.admin.db8e3c2aab1b": "♻️ Restart completed. Successful: <b>",
    "telegram.routers.admin.dc29a65d9fce": "💎 Select a game to manage plans:",
    "telegram.routers.admin.ddbf294803bb": " and central server",
    "telegram.routers.admin.df57673be486": "</b>\nVisible to users: <b>",
    "telegram.routers.admin.e33ec6f3b000": "The plan is invalid or disabled.",
    "telegram.routers.admin.e53ba1568def": " hours</b>\nAutomatic backup: <b>",
    "telegram.routers.admin.e7403baec99c": " seconds</b>\nUsers with access: <b>",
    "telegram.routers.admin.eb06b38998b0": "Send the trial duration in minutes, for example: <code>120</code>.",
    "telegram.routers.admin.ed19db2e2b60": "👥 <b>Come To Molten Users</b> — ",
    "telegram.routers.admin.ef9e4c9226f3": "Public wallet address",
    "telegram.routers.admin.f0633dc70778": "</b>\nPrice: <b>",
    "telegram.routers.admin.f0e472867266": "No active account or subscription was found.",
    "telegram.routers.admin.f5acf1375c9a": "Update interval must be between 20 and 86400 seconds.",
    "telegram.routers.admin.f5adbce04e08": "Configured",
    "telegram.routers.admin.f6b6a8ffc618": "Send the maximum restart attempts per worker; 0 disables restarts.",
    "telegram.routers.admin.f747270e6189": "Format: <code>/extend ACCOUNT_ID DAYS</code>",
    "telegram.routers.admin.f9a04593afc0": "Enable the game first.",
    "telegram.routers.admin.f9c74d69d056": "Send the automatic backup interval in seconds; minimum 3600.",
    "telegram.routers.admin.fd05469df199": "</b>\nUpdate interval: <b>",
    "telegram.routers.admin.fec37b190eaa": "Send the required network confirmation count; minimum 1.",
}


def admin_literal(key: str) -> str:
    """Return an English administrator-interface string."""
    return ADMIN_TEXT.get(str(key), str(key))
